version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: questionmaster-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.swzkcdgnahprrfzpfaoi&password=LeuY2TDZ6zreGbPp
      DATABASE_USERNAME: postgres.swzkcdgnahprrfzpfaoi
      DATABASE_PASSWORD: LeuY2TDZ6zreGbPp
      JWT_SECRET: +zpR/X0Hgds89beVkgtFrnkqx8tzt0pJ/E0EE4emvHInj8XgHI8+AFR14eLzfoGBZ92vUe7TEwox6l8OCT8EMg==
      JWT_EXPIRATION: 86400000
    expose:
      - "8080"
    networks:
      - questionmaster-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: questionmaster-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api
    networks:
      - questionmaster-network
    restart: unless-stopped

networks:
  questionmaster-network:
    driver: bridge
